- name: Install fish shell
  hosts: desktops
  become: True
  # vars:
  tasks:
    - name: install apt packages
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
      become: True
      with_items:
        - git
        - curl
        - repository-properties-common
        - openssh-server
  # handlers:
- include: btrfs.yml
- include: fish.yml
- include: flatpaks.yml
- include: podman.yml
- include: libvirt.yml