# - name: Install the latest version of the fish shell, set it as the user's default login shell, and configure it
#   become: False
#   # vars:
#   #   current_user: "{{ ansible_user_id }}"
#   tasks:
- name: add the fish shell PPA
  become: True
  apt_repository:
    repo: ppa:fish-shell/release-3
- name: install apt packages
  become: True
  apt:
    pkg: {{ item }}
    update_cache: True
    cache_valid_time: 3600
  with_items:
    - fish
- name: add fish to login shells
  become: True
  shell: add-shell /usr/bin/fish
- name: set fish as the user's login shell
  user:
    name: jordan
    shell: /usr/bin/fish
- name: disable the fish shell greeting
  shell:
    executable: /usr/bin/fish
    cmd: set -U fish_greeting ""
- name: enable backwards-incompatible fish shell features
  shell:
    executable: /usr/bin/fish
    cmd: set -U fish_features stderr-nocaret qmark-noglob
- name: create the fish shell functions directory for the user
  file:
    path: ~/.config/fish/functions/
    state: directory
    mode: 0700
- name: style the fish shell prompt according to robbyrussell's prompt
  copy:
    src: /usr/share/fish/tools/web_config/sample_prompts/robbyrussell.fish
    dest: ~/.config/fish/functions/fish_prompt.fish
    mode: 0700
- name: set the fish shell color theme to Solarized Dark
  script:
    executable: fish
    cmd: set_fish_color_theme_to_solarized_dark.fish
# - name: reset ssh connection to switch to fish as the default login shell
#   meta: reset_connection
# handlers:
