---
# tasks file for ansible_fish
- name: add the fish shell PPA
  become: True
  ansible.builtin.apt_repository:
    repo: ppa:fish-shell/release-3
- name: install the fish package
  become: true
  ansible.builtin.apt:
    pkg: fish
    update_cache: true
    cache_valid_time: 3600
- name: allow fish as a login shell
  become: true
  ansible.builtin.lineinfile:
    line: /usr/bin/fish
    path: /etc/shells
    state: present
- name: set fish as the user's login shell
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /usr/bin/fish
  register: u
- name: create the user's fish config directory
  ansible.builtin.file:
    path: "{{ u.home }}/.config/fish/"
    state: directory
    mode: 0770
    owner: "{{ user }}"
- name: set the color theme to Solarized Dark and enable backwards-incompatible features
  ansible.builtin.copy:
    src: fish_variables
    dest: "{{ u.home }}/.config/fish_variables"
    mode: 0640
    owner: "{{ user }}"
- name: create the user's fish functions directory
  ansible.builtin.file:
    path: "{{ u.home }}/.config/fish/functions/"
    state: directory
    mode: 0770
    owner: "{{ user }}"
- name: disable the greeting message
  ansible.builtin.copy:
    src: fish_greeting.fish
    dest: "{{ u.home }}/.config/fish/functions/fish_greeting.fish"
    mode: 0640
    owner: "{{ user }}"
- name: style the prompt according to robbyrussell's prompt
  ansible.builtin.copy:
    src: /usr/share/fish/tools/web_config/sample_prompts/robbyrussell.fish
    dest: "{{ u.home }}/.config/fish/functions/fish_prompt.fish"
    mode: 0640
    owner: "{{ user }}"
