---
# tasks file for ansible_fish

- name: add the fish shell PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:fish-shell/release-3
- name: install the fish package
  become: true
  ansible.builtin.apt:
    pkg: fish
    update_cache: true
    cache_valid_time: 3600
- name: allow fish as a login shell
  become: true
  ansible.builtin.lineinfile:
    line: /usr/bin/fish
    path: /etc/shells
    state: present
- name: set fish as the user's login shell
  become: true
  become_user: "{{ user }}"
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /usr/bin/fish
  register: u
- name: enable backwards-incompatible features
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_features / {$1=""; print $0}'
      and set -U fish_features stderr-nocaret qmark-noglob
  register: previous
  changed_when: previous.stdout != " 'stderr-nocaret' 'qmark-noglob'"
- name: create the user's fish config directory
  become: true
  become_user: "{{ user }}"
  ansible.builtin.file:
    path: "{{ u.home }}/.config/fish/"
    state: directory
    mode: 0770
    owner: "{{ user }}"
- name: create the user's fish functions directory
  become: true
  become_user: "{{ user }}"
  ansible.builtin.file:
    path: "{{ u.home }}/.config/fish/functions/"
    state: directory
    mode: 0770
    owner: "{{ user }}"
- name: disable the greeting message
  become: true
  become_user: "{{ user }}"
  ansible.builtin.copy:
    src: fish_greeting.fish
    dest: "{{ u.home }}/.config/fish/functions/fish_greeting.fish"
    mode: 0640
    owner: "{{ user }}"
- name: style the prompt according to robbyrussell's prompt
  become: true
  become_user: "{{ user }}"
  ansible.builtin.copy:
    src: /usr/share/fish/tools/web_config/sample_prompts/robbyrussell.fish
    dest: "{{ u.home }}/.config/fish/functions/fish_prompt.fish"
    mode: 0640
    owner: "{{ user }}"

# Set fish color theme variables
- name: set fish_color_normal to normal
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_color_normal / {print $2}';
      and set -U fish_color_normal normal
  register: previous
  changed_when: previous.stdout != "normal"
- name: set fish_color_command to 93a1a1
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_color_command / {print $2}';
      and set -U fish_color_command 93a1a1
  register: previous
  changed_when: previous.stdout != "93a1a1"
- name: set fish_color_quote to 657b83
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_color_quote / {print $2}';
      and set -U fish_color_quote 657b83
  register: previous
  changed_when: previous.stdout != "657b83"
- name: set fish_color_redirection to 6c71c4
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_color_redirection / {print $2}';
      and set -U fish_color_redirection 6c71c4
  register: previous
  changed_when: previous.stdout != "6c71c4"
- name: set fish_color_error to dc322f
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_color_error / {print $2}';
      and set -U fish_color_error dc322f
  register: previous
  changed_when: previous.stdout != "dc322f"
- name: set fish_color_end to 268bd2
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_color_end / {print $2}';
      and set -U fish_color_end 268bd2
  register: previous
  changed_when: previous.stdout != "268bd2"
- name: set fish_color_selection to "white --bold --background=brblack"
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_color_selection / {$1=""; print $0}';
      and set -U fish_color_selection white --bold --background=brblack
  register: previous
  changed_when: previous.stdout != " 'white' '--bold' '--background=brblack'"
- name: set fish_color_search_match to "bryellow --background=black"
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_color_search_match / {$1=""; print $0}';
      and set -U fish_color_search_match bryellow --background=black
  register: previous
  changed_when: previous.stdout != " 'bryellow' '--background=black'"
- name: set fish_color_history_current to --bold
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_color_history_current / {print $2}';
      and set -U fish_color_history_current --bold
  register: previous
  changed_when: previous.stdout != "--bold"
- name: set fish_color_operator to 00a6b2
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_color_operator / {print $2}';
      and set -U fish_color_operator 00a6b2
  register: previous
  changed_when: previous.stdout != "00a6b2"
- name: set fish_color_param to 839496
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_color_param / {print $2}';
      and set -U fish_color_param 839496
  register: previous
  changed_when: previous.stdout != "839496"
- name: set fish_color_cwd to green
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_color_cwd / {print $2}';
      and set -U fish_color_cwd green
  register: previous
  changed_when: previous.stdout != "green"
- name: set fish_color_cwd_root to red
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_color_cwd_root / {print $2}';
      and set -U fish_color_cwd_root red
  register: previous
  changed_when: previous.stdout != "red"
- name: set fish_color_valid_path to --underline
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_color_valid_path / {print $2}';
      and set -U fish_color_valid_path --underline
  register: previous
  changed_when: previous.stdout != "--underline"
- name: set fish_color_autosuggestion to 586e75
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_color_autosuggestion / {print $2}';
      and set -U fish_color_autosuggestion 586e75
  register: previous
  changed_when: previous.stdout != "586e75"
- name: set fish_color_user to brgreen
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_color_user / {print $2}';
      and set -U fish_color_user brgreen
  register: previous
  changed_when: previous.stdout != "brgreen"
- name: set fish_color_escape to 00a6b2
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_color_escape / {print $2}';
      and set -U fish_color_escape 00a6b2
  register: previous
  changed_when: previous.stdout != "00a6b2"
- name: set fish_color_cancel to -r
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_color_cancel / {print $2}';
      and set -U fish_color_cancel -r
  register: previous
  changed_when: previous.stdout != "-r"
- name: set fish_pager_color_completion to B3A06D
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_pager_color_completion / {print $2}';
      and set -U fish_pager_color_completion B3A06D
  register: previous
  changed_when: previous.stdout != "B3A06D"
- name: set fish_pager_color_description to B3A06D
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_pager_color_description / {print $2}';
      and set -U fish_pager_color_description B3A06D
  register: previous
  changed_when: previous.stdout != "B3A06D"
- name: set fish_pager_color_description to B3A06D
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_pager_color_description / {print $2}';
      and set -U fish_pager_color_description B3A06D
  register: previous
  changed_when: previous.stdout != "B3A06D"
- name: set fish_pager_color_prefix to "cyan --underline"
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_pager_color_prefix / {$1=""; print $0}';
      and set -U fish_pager_color_prefix cyan --underline
  register: previous
  changed_when: previous.stdout != " 'cyan' '--underline'"
- name: set fish_pager_color_progress to "brwhite --background=cyan"
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_pager_color_progress / {$1=""; print $0}';
      and set -U fish_pager_color_progress brwhite --background=cyan
  register: previous
  changed_when: previous.stdout != " 'brwhite' '--background=cyan'"
- name: set fish_color_host to normal
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_color_host / {print $2}';
      and set -U fish_color_host normal
  register: previous
  changed_when: previous.stdout != "normal"
- name: set fish_color_match to --background=brblue
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_color_match / {print $2}';
      and set -U fish_color_match --background=brblue
  register: previous
  changed_when: previous.stdout != "--background=brblue"
- name: set fish_color_comment to 586e75
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    executable: /usr/bin/fish
    cmd: |
      set -U | awk '/fish_color_comment / {print $2}';
      and set -U fish_color_comment 586e75
  register: previous
  changed_when: previous.stdout != "586e75"
