---
- name: Converge
  hosts: all
  tasks:
    - name: Update Aptitude's package cache
      become: true
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts['os_family'] == "Debian"
    - name: Include ansible_fish
      include_role:
        name: "ansible_fish"
