---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: debian
    image: docker.io/pycontribs/debian
    pre_build_image: true
    groups:
      - Debian
  - name: fedora33
    image: docker.io/fedora:33
    pre_build_image: true
    groups:
      - Fedora
  - name: fedora34
    image: docker.io/fedora:34
    pre_build_image: true
    groups:
      - Fedora
  - name: ubuntu
    image: docker.io/pycontribs/ubuntu
    pre_build_image: true
    groups:
      - Debian
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false
verifier:
  name: ansible
lint: yamllint . && ansible-lint .
