---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: ubuntu
    image: pycontribs/ubuntu
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false
verifier:
  name: ansible
lint: yamllint . && ansible-lint .
